<?php
include_once("includes/database.php");
include_once("includes/utilities.php");

?>

<link rel="stylesheet" type="text/css" href="assets/css/style.css">
<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
<script src="assets/js/main.js"></script>


<body>
<div id="new-call-body">

    <div class="submit-form-fields">

        <form id="callform" method="post">

            <div class="section">
                <label>Date</label>
                <input type="text" id='date' name="date" placeholder="<?php echo date("d/m/Y")?>"disabled>
            </div>

            <div class="section">
                <label>Rules</label>
                <input type="text" id="rules" name="rules" placeholder="First In First Out (FIFO)" disabled>
            </div>

            <div class="section">
                <label>Investment Name</label>
                <input type="text" id="name" name="name" value="<?php echo 'Investment' . ' '. ++$id ?>"readonly>
            </div>

            <div class="section">
                <label>Capital Required for Investment</label>
                <input id='currency' placeholder="$" disabled>
                <input id="capital" type="text" name="capital" value="10,000,000">
            </div>

            <input type="submit" id="calculate" value="Calculate">

        </form>

    </div>

    <?php

    if (isset($_POST["capital"])) {
        //strip tags - removes threat of sql injection...
        $paramCapital = strip_tags($_POST["capital"]);
        $paramCapital = turnIntoFloat($paramCapital);
        $paramName = strip_tags($_POST['name']);
        $usDate = date('Y/m/d');

    }

    ?>

        <div class="commitment-table">

            <table id="commitment">
                <tr>
                    <th>Commitment_ID</th>
                    <th>Fund_ID </th>
                    <th>Date</th>
                    <th>Fund</th>
                    <th>Commited Amounts</th>
                    <th>Undrawn Capital Commitment before Current Drawdown Notice</th>
                    <?php if (isset($_POST['capital'])) : ?>
                    <th>Total Drawdown Notice</th>
                    <th>Undrawn Capital Commitment after Current Drawdown Notice</th>
                    <?php endif; ?>
                </tr>

                <tr>
                    <?php foreach (getCommitmentData() as $commitmentData) :?>
                        <?php
                        $commitmentId = $commitmentData['id'];
                        $commitmentFund = $commitmentData['fund_id'];
                        $commitmentDate = $commitmentData['date'];
                        $commitmentAmount = $commitmentData['amount'];

                        $ukDate =  date("d/m/Y", strtotime($commitmentDate));
                        $beforeCurrentNotice = beforeCurrentNotice($commitmentId, $commitmentAmount);

                        if (isset($_POST["capital"])) {
                            if ($paramCapital > 0) {
                                $totalNotice = totalNotice($paramCapital, $beforeCurrentNotice);
                                $paramCapital = $paramCapital - $totalNotice;

                            } else{
                                $totalNotice = 0;
                            }

                            $undrawnCapital = undrawnCapital($beforeCurrentNotice, $totalNotice);

                        }


                        ?>
                    <td><strong><?php echo $commitmentId ?></strong></td>
                    <td><strong><?php echo $commitmentFund ?></strong></td>
                    <td><?php echo $ukDate ?></td>
                    <td style="text-align: left;"><?php echo 'fund '. $commitmentFund ?></td>
                    <td><?php echo $commitmentAmount ?></td>
                    <td><?php echo $beforeCurrentNotice ?></td>
                    <?php if (isset($_POST['capital'])) : ?>
                    <td class="hidden-input"><?php echo $totalNotice ? number_format($totalNotice, 2) : '-' ?></td>
                    <td class="hidden-input"><?php echo $undrawnCapital ? number_format($undrawnCapital, 2): '-' ?></td>
                    <?php endif;?>
                </tr>

                <?php endforeach ?>
            </table>
        </div>
</div>
</body>


<script type="text/javascript">

    jQuery(document).ready(function ($) {

        $('#calculate').click(function () {

            var form = $("#callform");

            $(form).submit();

            // alert('test');
            // now only fires once..
            $(this).css('background-color', 'gray');
            $(this).prop('disabled', true);

        });

    });

</script>
